# See https://docs.github.com/en/actions/guides for documentation about GitHub
# Actions.

name: Validation Tests

# Run on all branches.
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    # Tried to use
    # https://github.com/actions/checkout#Checkout-multiple-repos-side-by-side,
    # but it looks like GITHUB_WORKSPACE is set to
    # /home/runner/work/AceTime/AceTime, so if path is set to 'main' as
    # suggested in the article, then the repos is set to
    # /home/runner/work/Acetime/AceTime/main/AceTime, which is really
    # confusing. Instead, use 'cd ..' to go up a level and call 'git clone'
    # manually.
    steps:
    - name: Checkout AceTime
      uses: actions/checkout@v3

    - name: Checkout Additional Repos
      run: |
        cd ..
        git clone --depth 1 https://github.com/bxparks/EpoxyDuino
        git clone --depth 1 https://github.com/bxparks/AUnit
        git clone --depth 1 https://github.com/bxparks/AceCommon
        git clone --depth 1 https://github.com/bxparks/AceSorting
        git clone --depth 1 https://github.com/bxparks/AceTime
        git clone --depth 1 https://github.com/bxparks/AceTimeC
        git clone --depth 1 https://github.com/bxparks/AceTimeTools
        git clone --depth 1 https://github.com/bxparks/AceTimePython
        git clone --depth 1 https://github.com/HowardHinnant/date
        git clone https://github.com/eggert/tz

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ../AceTimeTools/requirements.txt
        pip install -r ../AceTimePython/requirements.txt
        pip install -e ../AceTimeTools
        pip install -e ../AceTimePython

    - name: Install Go lang
      uses: actions/setup-go@v3
      with:
        go-version: 'stable'

    - name: Install libcurl4-openssl-dev
      run: |
        sudo apt update
        sudo apt install -y libcurl4-openssl-dev

    - name: Validate Python Compare tools
      run: |
        make -C tools python

    - name: Build Other Compare tools
      run: |
        make -C ../AceTimeC/src
        make -C tools/compare_acetimec
        make -C tools/compare_cpp
        make -C tools/compare_c
        make -C tools/compare_go

    - name: Validations
      run: |
        make validations

    # Run the validation tests which will succeed when the TZDB version is
    # updated (BasicHinnantDateTest, ExtendedHinnantDateTest, BasicAcetzTest,
    # ExtendedAcetzTest). We don't run the others because when a new TZDB
    # version comes out, the Python pytz, dateutil, and Java validation tests
    # will always fail because they depend on the obsolete TZ database on the
    # host Operating System.
    - name: RunValidations
      run: |
        make runvalidations
